# Generated by Django 2.2.5 on 2019-09-06 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Musicas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=255)),
                ('Artista', models.CharField(max_length=255)),
                ('Genero', models.CharField(max_length=50)),
            ],
        ),
    ]
