# Generated by Django 2.2.5 on 2019-09-06 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='musicas',
            old_name='Genero',
            new_name='Genero_musical',
        ),
        migrations.RenameField(
            model_name='musicas',
            old_name='Nome',
            new_name='Nome_Musica',
        ),
    ]
