# Generated by Django 2.2.5 on 2019-09-06 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicas', '0002_auto_20190906_1946'),
    ]

    operations = [
        migrations.RenameField(
            model_name='musicas',
            old_name='Genero_musical',
            new_name='Genero',
        ),
        migrations.RenameField(
            model_name='musicas',
            old_name='Nome_Musica',
            new_name='Nome',
        ),
    ]
