# Generated by Django 2.2.5 on 2019-09-06 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicas', '0003_auto_20190906_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicas',
            name='Artista',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='musicas',
            name='Nome',
            field=models.CharField(max_length=50),
        ),
    ]
