# Generated by Django 2.2.5 on 2019-09-06 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicas', '0004_auto_20190906_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicas',
            name='Musical',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
